name: b-react-vite deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        env:
          VITE_APP_ENV: ${{ secrets.VITE_APP_ENV }}
        run: |
          echo VITE_APP_ENV=$VITE_APP_ENV >> .env

      - name: Build React app
        run: npm run build
